# Generated by Django 4.1.7 on 2023-03-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_by_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='by_subscription',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=10, verbose_name='По подписке'),
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(choices=[('США', 'США'), ('Россия', 'Россия'), ('Великобритания', 'Великобритания'), ('Франция', 'Франция'), ('Япония', 'Япония')], default='США', max_length=50, verbose_name='Страна'),
        ),
    ]
