# Generated by Django 4.1.7 on 2023-04-06 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
